version: '3'
services:
  db:
    image: postgres:9-alpine

  setup:
    build: .
    command:
      - setup-database
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/bathroom_finder

  app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - setup
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/bathroom_finder
