apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - image: postgres:9-alpine
      name: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: bathroom
        - name: POSTGRES_PASSWORD
          value: finder

---

apiVersion: v1
kind: Service

metadata:
  name: postgres

  labels:
    app: postgres

spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP

  selector:
    app: postgres
